/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Auction data structure for the Auctiondeal platform
 */
export interface Auction {
  /**
   * Unique identifier for the auction
   */
  id: string;
  /**
   * Current status of the auction
   */
  status: "active" | "cancelled" | "completed";
  /**
   * Date when the auction takes place
   */
  auctionDate: string;
  /**
   * Time when the auction starts
   */
  auctionTime?: string;
  /**
   * Location where the auction takes place
   */
  auctionLocation?: string;
  /**
   * Deadline for auction registration
   */
  registrationDeadline?: string;
  /**
   * Deadline for circulation
   */
  circulationDeadline?: string;
  /**
   * Office responsible for the auction
   */
  responsibleOffice?: string;
  /**
   * Additional legal remedy information
   */
  additionalLegalRemedy?: string;
  /**
   * Timestamp when the record was created
   */
  createdAt?: string;
  /**
   * Timestamp when the record was last updated
   */
  updatedAt?: string;
}
