/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SHAB publication data from Swiss Commercial Gazette
 */
export interface ShabPublication {
  /**
   * Unique identifier for the SHAB publication record
   */
  id: string;
  /**
   * SHAB meta ID for tracking
   */
  metaId: string;
  /**
   * SHAB publication number
   */
  publicationNr: string;
  /**
   * SHAB subsection identifier
   */
  subsectionId: string;
  /**
   * Date when the publication was issued
   */
  publicationDate: string;
  /**
   * Complete XML content for audit trail and reprocessing
   */
  xmlContent: string;
  /**
   * Timestamp when the publication was processed
   */
  processedAt?: string;
  /**
   * Status of the processing pipeline
   */
  processingStatus?: "pending" | "processed" | "failed" | "skipped";
  /**
   * Results from LLM extraction process
   */
  extractionResults?: {
    [k: string]: unknown;
  };
  /**
   * Timestamp when the record was created
   */
  createdAt?: string;
  /**
   * Timestamp when the record was last updated
   */
  updatedAt?: string;
}
